from random import randint
from time import sleep

characters = {
    "Jack": {"strength": 2, "intelligence": 3, "stamina": 5,},
    "007n7": {"strength": 1, "intelligence": 4, "stamina": 5,},
    "Shedletsky": {"strength": 4, "intelligence": 3, "stamina": 3,},
    "Guest": {"strength": 5, "intelligence": 1, "stamina": 4, },
    "Chance": {"strength": randint(1, 5), "intelligence": randint(1, 5), "stamina": randint(1, 5), },
    "Two Time": {"strength": 5, "intelligence": 3, "stamina": 2,},
    "Elliot": {"strength": 0, "intelligence": 5, "stamina": 5,},
    "Dusekkar": {"strength": 1, "intelligence": 7, "stamina": 2,},
    "Taph": {"strength": 2, "intelligence": 6, "stamina": 2,},
    "Builderman": {"strength": 1, "intelligence": 8, "stamina": 1,}
}
the_final_decision = randint(1,1000)
def calcular_totais(char_list):
    total_strength = sum(characters[name]["strength"] for name in char_list)
    total_intelligence = sum(characters[name]["intelligence"] for name in char_list)
    total_stamina = sum(characters[name]["stamina"] for name in char_list)
    return total_strength, total_intelligence, total_stamina
Escolha = input("START GAME? yes | no : ")
Escolha = Escolha.capitalize()
if Escolha == "No":
    sleep(0.5)
    print("ok, whenever you want to start, tell me")
elif Escolha == "Yes":
    sleep(0.5)
    print("Let's do this")
    sleep(0.5)
    print("you were trapped by an entity called 'The spectre'")
    sleep(2)
    print("He tortures people for fun, and he is know to be merciless")
    sleep(2.75)
    print("you and your colleagues are going to enter the limbo")
    sleep(2)
    print("and the reward of entering and gettin out is freedom ")
    sleep(1.75)
    print("The people who are going with you are:")
    sleep(1.5)
    print("Jack - yourself")
    sleep(1.5)
    print("007n7 - hacker who literally made chaos")
    sleep(3)
    print("Shedletsky - your best friend")
    sleep(2)
    print("Guest - a war veteran")
    sleep(1.5)
    print("Chance - a gambler")
    sleep(1.5)
    print("Two Time - killer who sacrificed his best friend for his cult (the respawn)")
    sleep(3.5)
    print("Elliot - Chef who we do not know how the hell he ended up there")
    sleep(3.5)
    print("Dusekkar - A wizard")
    sleep(1.5)
    print("Taph - A bomber who cannot speak")
    sleep(1.5)
    print("Builderman - the creator of the creature")
    sleep(2)
    print("But someone has to be left behind, to make sure the plan does not raise suspicion")
    sleep(2)
    while True:
        escolha_personagem = input("Who will it be? ")
        escolha_personagem.capitalize()
        if escolha_personagem in characters:
            print(f"{escolha_personagem} was abandoned.")
            sleep(1)
            if escolha_personagem == "Jack":
                print("You decided to be left behind.")
                sleep(1.5)
                print("For the best of them.")
                sleep(1.5)
                print("But HE sees you and wants to know where they are.")
                sleep(1.5)
                final1_2 = input("Will you snitch? yes | no : ")
                final1_2.capitalize()
                if final1_2 == "Yes":
                    print("You decided to tell the truth.")
                    sleep(1.5)
                    print("So as a reward you are free.")
                    sleep(1.5)
                    print("But you're forced to see your friends die.")
                    sleep(1.5)
                    print("While they know you snitched on them.")
                    sleep(1.5)
                    print("Ending 1: The Snitch - You won, but at what cost?")
                    exit()
                elif final1_2 == "No":
                    print("You decided to lie.")
                    sleep(1.5)
                    print("He respects your decision, but kills you for tricking him.")
                    sleep(1.5)
                    print("Ending 2: Heroic Ending - You sacrificed yourself and are remembered.")
                    exit()
            else:
                del characters[escolha_personagem]
                total_strength, total_intelligence, total_stamina = calcular_totais(characters)
                print(f"Survivors still alive:")
                for p in characters:
                    print(f"- {p}")
                    sleep(1)
                print(f"\nTotal Strength: {total_strength}")
                print(f"Total Intelligence: {total_intelligence}")
                print(f"Total Stamina: {total_stamina}")
                break
    print("your group continues onward")
    sleep(1.5)
    print("But you sense a mysterious ")
    sleep(1.5)
    print("someone who wants revenge")
    sleep(1.5)
    print("A masked man comes rushin towards you ")
    sleep(1.5)
    print("You have to options:")
    sleep(1.5)
    print("1 : flee with everyone")
    sleep(1.5)
    print("2 : abandon someone to have enough time to escape")
    sleep(1.5)
    decisao1 = input("what will you do? Abandon | Flee ")
    sleep(1.5)
    if decisao1 == "Flee":
        if total_stamina >= 32:
            print("Your team got away without a scratch")
            sleep(1.5)
        else:
            print("Your team tried to escape")
            sleep(1.5)
            print("but he catched up to the group")
            sleep(1.5)
            print("and everyone died to the man")
            sleep(1.5)
            print("Ending 3: Brutality - everyone in tyhe group died to Jason. Tip: he is very fast, so choose to flee if you have a very high group stamina")
            exit()
    elif decisao1 == "Abandon":
        while True:
            escolha_personagem2 = input("Who will it be?").strip().title()
            if escolha_personagem2 in characters:
                print(f"{escolha_personagem2} was abandoned.")
                sleep(1.5)
                if escolha_personagem2 == "Jack":
                    print("you decided to sacrifice yourself")
                    sleep(1.5)
                    print("Ending 4 : Forsakened - you died")
                    exit()
                else:
                    del characters[escolha_personagem2]
                    total_strength, total_intelligence, total_stamina = calcular_totais(characters)
                    print(f"Survivors still alive:")
                    for p in characters:
                        print(f"- {p}")
                        sleep(1)
                    print(f"\nTotal Strength: {total_strength}")
                    print(f"Total Intelligence: {total_intelligence}")
                    print(f"Total Stamina: {total_stamina}")
                    break
    print("after escaping Jason, you spot a Carnival")
    sleep(1.5)
    print("but something feels odd")
    sleep(1.5)
    print("everyone there is red and not moving")
    sleep(1.5)
    print("The child of 007n7, Coolkidd, corrupted by The Spectre, standing there, thinking everything is just a game")
    sleep(1.5)
    print("Someone has to play his little game to move on")
    sleep(1.5)

    while True:
        escolha_personagem3 = input("Who will it be? ").strip().title()
        if escolha_personagem3 in characters:
            print(f"{escolha_personagem3} was abandoned.")
            sleep(1.5)
            if escolha_personagem3 == "Jack":
                print("you decided to sacrifice yourself")
                sleep(1.5)
                print("Ending 4 : Forsakened - you died")
                exit()

            elif escolha_personagem3 == "007n7":
                print("007n7 was left behind")
                sleep(1.5)
                print("But the spectre appears out of nowhere and gives an offer to him")
                sleep(1.5)
                print("If he captured everyone in the group")
                sleep(1.5)
                print("Not only he would get his freedom, but he would give him his son back")
                sleep(1.5)
                print("As a father who failed once, he decides to capture the entire group")
                sleep(1.5)
                print("And in the end, he got his freedom as well as his son, while you and the rest got locked up")
                sleep(1.5)
                print("Ending 5: Reunited - you got locked up in that realm forever while 007n7 and Coolkidd got their freedom")
                exit()
            else:
                del characters[escolha_personagem3]
                total_strength, total_intelligence, total_stamina = calcular_totais(characters)
                print(f"Survivors still alive:")
                for p in characters:
                    print(f"- {p}")
                    sleep(1.5)
                print(f"\nTotal Strength: {total_strength}")
                print(f"Total Intelligence: {total_intelligence}")
                print(f"Total Stamina: {total_stamina}")
                break
    print("after that incident, the survivors stumble upon a place... blockified?")
    sleep(1.5)
    print("you also notice corruption, black goo with red 0s and 1s")
    sleep(1.5)
    print("A black figure with a crown, covered in 0s and 1s, appears from behind")
    sleep(1.5)
    print("He knows that you are trying to escape the master's hands")
    sleep(1.5)
    print("he will not allow that to happen")
    sleep(1.5)
    print("he affirms that the place they had to go through has been setted up with traps")
    sleep(1.5)
    print("he gives 2 options")
    sleep(1.5)
    print("you could try to go through the zone with traps")
    sleep(1.5)
    print("or go through him")
    sleep(1.5)
    decisao2 = input("what will you do? Fight | Go through the place (Note: if you choose this option, you have to put 'go' and not the full sentence) ")
    decisao2.capitalize()
    sleep(1.5)
    if decisao2 == "Fight":
        if total_strength >= 20:
            print("Your team decided to fight him")
            sleep(1.5)
            print("Your team defeated him")
            sleep(1.5)
        else:
            print("Your team decided to fight him")
            sleep(1.5)
            print("he destroyed the survivors")
            sleep(1.5)
            print("it was not even close")
            sleep(1.5)
            print("Ending 6: Fatality  - everyone in the group died to John Doe. Tip: he is strong, so choose to fight if you have a high group strength")
            exit()
    elif decisao2 == "Go":
        if total_intelligence >= 30:
            print("Your team decided to go through the place with traps")
            sleep(1.5)
            print("The survivors evaded all of the traps")
            sleep(1.5)
            print("And as a reward, he lets you through")
        else:
            print("Your team decided to go through the place with traps")
            sleep(1.5)
            print("the survivors tried their best, but they got destroyed, one by one, by bombs and toxic fog")
            sleep(1.5)
            print("Ending 6: Fatality - everyone in the group died to John Doe's traps. Tip: he is very smart, so choose to go if you have a high group intelligence")
            exit()
    print("After dealing with John Doe, your group arrived at the final obstacle")
    sleep(1.5)
    print("a golden room")
    sleep(1.5)
    print("with an arena and a throne")
    sleep(1.5)
    print("a man descends from the throne")
    if "Shedletsky" in characters:
        print("your best friend is shocked")
        sleep(1.5)
        print("It is non other than his other half part of his soul")
        sleep(1.5)
        print("His hatred")
    sleep(1.5)
    print("shining in golden, with two cursed swords, the 'Mythic Swords of the West Wind'")
    sleep(1.5)
    print("In order to get your freedom, one from your team has to defeat the legendary king")
    sleep(1.5)
    while True:
        print(f"Characters still alive:")
        for p in characters:
            print(f"- {p}")
            sleep(1)
        escolha_personagem4 = input("Who will it be?")
        escolha_personagem4.capitalize()
        if escolha_personagem4 in characters:
            print(f"{escolha_personagem4} was chosen.")
            sleep(1.5)
            if escolha_personagem4 == "Jack":
                print("you decided to fight him")
                sleep(1.5)
                print("you lost miserably")
                sleep(1.5)
                print("Ending 4 : Forsakened - you died")
                exit()
            elif escolha_personagem4 == "Shedletsky":
                print("They had a brutal duel")
                sleep(1.5)
                print("but in the end...")
                sleep(1.5)
                if the_final_decision >= 500:
                    print("the king of the heights has returned")
                    sleep(1.5)
                    print("his own hatred lost the title")
                    sleep(1.5)
                    print("And with his mighty power and bravery, he destroyed the spectre's curse")
                    sleep(1.5)
                    print("setting every survivor free")
                    sleep(1.5)
                    print("Ending 7: Champion of The Heights - been setted free by your best friend")
                    exit()
                else:
                    print("your best friend has fallen to the wrath of his own hatred")
                    sleep(1.5)
                    print("and with his power, his hatred annihilated every single person left")
                    sleep(1.5)
                    print("Ending 7: Corrupted champion's triumph - Everyone died to the champion")
                    exit()
            elif escolha_personagem4 == "Two Time" or "Guest":
                print("After a long duel")
                sleep(1.5)
                print(f"{escolha_personagem4} has won, but fell from fatigue")
                del characters[escolha_personagem4]
                total_strength, total_intelligence, total_stamina = calcular_totais(characters)
                sleep(1.5)
                print("he was defeated")
                sleep(1.5)
                print("And so")
                sleep(1.5)
                print("you and the rest of the survivors get your freedom")
                sleep(1.5)
                print("or so you thought")
                sleep(1.5)
                print("The spectre appears and reveals that this was all a mind game to entertain him")
                sleep(1.5)
                print("And that no could escape without him noticing")
                sleep(1.5)
                print("In disbelief, the survivors decide to do an all-out attack on the spectre")
                if total_strength < 18:
                    print("Your team was not strong enough")
                    sleep(1.5)
                    print("As a result, everyone got knocked out")
                    sleep(1.5)
                    print("And you did this journey for nothing")
                    sleep(1.5)
                    print("Ending 8: Spectre's show - 'thanks for playing your part in my show'")
                elif total_intelligence < 25:
                    print("Your team did not predict his movements")
                    sleep(1.5)
                    print("As a result, everyone got knocked out")
                    sleep(1.5)
                    print("And you did this journey for nothing")
                    sleep(1.5)
                    print("Ending 8: Spectre's show - 'thanks for playing your part in my show'")
                elif total_stamina < 25:
                    print("Your team couldn't dodge the attacks")
                    sleep(1.5)
                    print("As a result, everyone got knocked out")
                    sleep(1.5)
                    print("And you did this journey for nothing")
                    sleep(1.5)
                    print("Ending 8: Spectre's show - 'thanks for playing your part in my show'")
                else:
                    print("Your team attacked him non-stop")
                    sleep(1.5)
                    print("stabbing, punching, shooting, slashing, and more")
                    sleep(1.5)
                    print("In the end, he did not stand a chance")
                    sleep(1.5)
                    print("And the survivors escaped his terror")
                    sleep(1.5)
                    print("Ending 8: freedom - you win")
                sleep(1.5)
                print(f"Survivors:")
                for p in characters:
                    print(f"- {p}")
                    sleep(1.5)
                    exit()
            else:
                print("although he putted up a good fight")
                sleep(1.5)
                print(f" {escolha_personagem4} lost the duel and became one of this champion's fallen victims")
                del characters[escolha_personagem4]
                total_strength, total_intelligence, total_stamina = calcular_totais(characters)
                print(f"Still alive:")
                for p in characters:
                    print(f"- {p}")
                    sleep(1)
                print(f"\nTotal Strength: {total_strength}")
                print(f"Total Intelligence: {total_intelligence}")
                print(f"Total Stamina: {total_stamina}")